version: '3.9'

services:
  db:
    image: postgres:latest
    container_name: models
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USERNAME}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - PGDATA=/var/lib/postgresql/data/
    volumes:
      - postgresql_db_data:/var/lib/postgresql/data/
    ports:
      - 5432:5432

  db_editor:
    image: adminer
    container_name: db_editor
    restart: always
    env_file:
      - .env
    ports:
      - 8080:8080
    depends_on:
      - db

  redis:
    image: redis
    container_name: redis
    volumes:
      - redis_data:/data
    env_file:
      - .env
    expose:
      - 6379
    ports:
      - "6379:6379"
    sysctls:
      - net.core.somaxconn=1024
    command:
      redis-server --bind 0.0.0.0 --requirepass ${REDIS_PASSWORD}

  backend_app:
    container_name: backend_app
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./backend/
    volumes:
      - ./backend/:/usr/backend/
    expose:
      - 8000
    ports:
      - 8000:8000
    depends_on:
      - db
      - redis
    env_file:
      - .env

volumes:
  postgresql_db_data:
  redis_data:
